name: folio
description: A mobile app to help update and edit your website

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_storage: any
  url_launcher: ^5.4.2
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+2
  google_sign_in: ^4.1.4
  font_awesome_flutter: ^8.7.0
  google_fonts: any
  image_picker: any
  intl: any
  file_picker: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/